# -*- coding: utf-8 -*-
"""YZT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5mgbrS9CTREnOi7ZkGQ8ReLdu4RPQyx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# Aşama 1: Veri Yükleme ve Hazırlık (Pandas)



"""

data = pd.read_csv('movies_initial.csv')
data.head()

data = data[["imdbID" , "title" , "director", "genre", "imdbRating" , "imdbVotes"]]

data.head()

data.dtypes

df_copy = data.copy()

for col in df_copy.columns:
    if df_copy[col].dtypes == 'object':
        df_copy[col] = df_copy[col].astype('string')
    else:
        df_copy[col] = df_copy[col].astype('float64')
data = df_copy

data.dtypes

data.head()

data.isnull().sum()

import pandas as pd

df_coppy = data.copy()
for col in df_coppy.columns:
    if df_coppy[col].isnull().sum() > 0 and df_coppy[col].dtypes == 'float64':
        df_coppy[col].fillna(df_coppy[col].mean(), inplace=True)
    if df_coppy[col].isnull().sum() > 0 and df_coppy[col].dtypes == 'string':
        df_coppy[col].fillna("Unknown",inplace=True)
data = df_coppy

data.isnull().sum()

"""# Aşama 2: Keşifsel Veri Analizi (EDA) (Pandas & Numpy)"""

data.head()

data.describe().T

data.dtypes

data.info()

data.shape

"""# Aşama 3: Veri Görselleştirme (Matplotlib)"""

# hepsini aldığımda grafik karışık gözüktüğü için ilk 1000 tanesini aldım.
plt.figure(figsize=(10, 6))
plt.scatter(data['imdbVotes'][0:1000], data['imdbRating'][0:1000], alpha=0.5, color='purple')
plt.title('IMDb Puanı ve Oy Sayısı İlişkisi')
plt.xlabel('IMDb Oy Sayısı')
plt.ylabel('IMDb Puanı')
plt.grid(True)
plt.xscale('log')
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(data['imdbRating'].dropna(), bins=30, color='skyblue', edgecolor='black')
plt.title('IMDb Puanlarının Dağılımı (Histogram)')
plt.xlabel('IMDb Puanı')
plt.ylabel('Film Sayısı (Frekans)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()